name: Build Release

on:
  workflow_dispatch

jobs:
  build:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v3
       - name: Setup JAVA 17
         uses: actions/setup-java@v3
         with:
           java-version: '17'
           distribution: 'temurin'
           cache: gradle
 
      #1     
       - name: Decode Keystore
         env:
           ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
 
         run: |
           mkdir -p keystore
           echo $ENCODED_STRING > keystore/keystore-b64.txt
           base64 -d keystore/keystore-b64.txt > keystore/keystore.jks
           
       #2
       - name: Prepare Keystore variables
         run: |
           echo "keystore_path=keystore/keystore.jks &>> local.properties
           echo "keystore_password=${{secrets.SIGNING_KEY_PASSWORD}}" &>> local.properties
           echo "keystore_key_alias=${{secrets.SIGNING_KEY_ALIAS}}" &>> local.properties
           echo "keystore_key_password=${{secrets.SIGNING_STORE_PASSWORD}}" &>> local.properties

       - name: Grant execute permission for gradlew
         run: chmod +x gradlew

       - name: Build AAB with Gradle
         run: ./gradlew :app:bundleRelease

       - name: Update AAB to artifactory
         uses: actions/upload-artifact@v3
         with:
           name: release-app-bundle
           path: app/build/outputs/
           retention-days: 1
